name: Quotex Telegram Alerts

on:
  push:
    branches:
      - master
  workflow_dispatch:  # Manual trigger option

jobs:
  notify-telegram:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Send Telegram Notification
        run: |
          # Latest commit info
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          COMMIT_AUTHOR=$(git log -1 --pretty=%an)
          REPO_NAME="${{ github.repository }}"
          ESCAPED_MESSAGE=$(echo "$COMMIT_MESSAGE" | sed 's/"/\\"/g')

          MESSAGE="📢 Quotex AI Update!\n\nRepository: $REPO_NAME\nAuthor: $COMMIT_AUTHOR\nCommit Message: $ESCAPED_MESSAGE"

          # Send Telegram message (Direct Token + Chat ID)
          curl -s -X POST "https://api.telegram.org/bot8453457741:AAFLXRU15IlXLR5bFgAXzNzRQo6OeYfLYBo/sendMessage" \
            -H "Content-Type: application/json" \
            -d "{\"chat_id\": \"6439861365\", \"text\": \"$MESSAGE\", \"parse_mode\": \"Markdown\"}"

      - name: Optional: Run Python Script
        run: |
          # Uncomment to run your Quotex AI script
          # python3 quotex_ai_bot.py